export const currencyList = [
  { value: 'EUR', label: 'Euro' },
  { value: 'USD', label: 'US Dollar' },
  { value: 'JPY', label: 'Japanese Yen' },
  { value: 'BGN', label: 'Bulgarian Lev' },
  { value: 'CZK', label: 'Czech Republic Koruna' },
  { value: 'DKK', label: 'Danish Krone' },
  { value: 'GBP', label: 'British Pound Sterling' },
  { value: 'HUF', label: 'Hungarian Forint' },
  { value: 'PLN', label: 'Polish Zloty' },
  { value: 'RON', label: 'Romanian Leu' },
  { value: 'SEK', label: 'Swedish Krona' },
  { value: 'CHF', label: 'Swiss Franc' },
  { value: 'ISK', label: 'Icelandic Króna' },
  { value: 'NOK', label: 'Norwegian Krone' },
  { value: 'HRK', label: 'Croatian Kuna' },
  { value: 'RUB', label: 'Russian Ruble' },
  { value: 'TRY', label: 'Turkish Lira' },
  { value: 'AUD', label: 'Australian Dollar' },
  { value: 'BRL', label: 'Brazilian Real' },
  { value: 'CAD', label: 'Canadian Dollar' },
  { value: 'CNY', label: 'Chinese Yuan' },
  { value: 'HKD', label: 'Hong Kong Dollar' },
  { value: 'IDR', label: 'Indonesian Rupiah' },
  { value: 'ILS', label: 'Israeli New Sheqel' },
  { value: 'INR', label: 'Indian Rupee' },
  { value: 'KRW', label: 'South Korean Won' },
  { value: 'MXN', label: 'Mexican Peso' },
  { value: 'MYR', label: 'Malaysian Ringgit' },
  { value: 'NZD', label: 'New Zealand Dollar' },
  { value: 'PHP', label: 'Philippine Peso' },
  { value: 'SGD', label: 'Singapore Dollar' },
  { value: 'THB', label: 'Thai Baht' },
  { value: 'ZAR', label: 'South African Rand' }
]
