export const currencyList = [
  { code: 'EUR', country: 'Euro' },
  { code: 'USD', country: 'US Dollar' },
  { code: 'JPY', country: 'Japanese Yen' },
  { code: 'BGN', country: 'Bulgarian Lev' },
  { code: 'CZK', country: 'Czech Republic Koruna' },
  { code: 'DKK', country: 'Danish Krone' },
  { code: 'GBP', country: 'British Pound Sterling' },
  { code: 'HUF', country: 'Hungarian Forint' },
  { code: 'PLN', country: 'Polish Zloty' },
  { code: 'RON', country: 'Romanian Leu' },
  { code: 'SEK', country: 'Swedish Krona' },
  { code: 'CHF', country: 'Swiss Franc' },
  { code: 'ISK', country: 'Icelandic Króna' },
  { code: 'NOK', country: 'Norwegian Krone' },
  { code: 'HRK', country: 'Croatian Kuna' },
  { code: 'RUB', country: 'Russian Ruble' },
  { code: 'TRY', country: 'Turkish Lira' },
  { code: 'AUD', country: 'Australian Dollar' },
  { code: 'BRL', country: 'Brazilian Real' },
  { code: 'CAD', country: 'Canadian Dollar' },
  { code: 'CNY', country: 'Chinese Yuan' },
  { code: 'HKD', country: 'Hong Kong Dollar' },
  { code: 'IDR', country: 'Indonesian Rupiah' },
  { code: 'ILS', country: 'Israeli New Sheqel' },
  { code: 'INR', country: 'Indian Rupee' },
  { code: 'KRW', country: 'South Korean Won' },
  { code: 'MXN', country: 'Mexican Peso' },
  { code: 'MYR', country: 'Malaysian Ringgit' },
  { code: 'NZD', country: 'New Zealand Dollar' },
  { code: 'PHP', country: 'Philippine Peso' },
  { code: 'SGD', country: 'Singapore Dollar' },
  { code: 'THB', country: 'Thai Baht' },
  { code: 'ZAR', country: 'South African Rand' }
]
